apiVersion: batch/v1
kind: Job
metadata:
  name: hi
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hi
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure